networks:
  apparchitecture:
    driver: bridge

services:
  architecture:
    ports:
      - 8000:8080
    container_name: architecture
    build: .
    volumes:
      - data_protection_keys:/home/app/.aspnet/DataProtection-Keys
    depends_on:
      - appdb
    environment:
      - DB_HOST=app-db
      - DB_NAME=dbname
      - DB_SA_PASSWORD=password@12345#
    networks:
      - apparchitecture
  appdb:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - db_data_volume:/var/opt/mssql
    ports:
      - 8002:1433
    environment:
      - SA_PASSWORD=password@12345#
      - ACCEPT_EULA=Y
    networks:
      - apparchitecture
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=app-db
    networks:
      - apparchitecture

volumes:
  data_protection_keys:
  db_data_volume: